---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: collection
  namespace: '{{ .Release.Namespace }}'
spec:
  mode: deployment
  replicas: {{ .Values.replicas | int }}
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            # Just an example, this is weird to do
            endpoint: ${env:OTELCOL_HTTP_ENDPOINT}
    processors:

    exporters:
      debug:

    service:
      pipelines:
        trace:
          receivers: [otlp]
          processors: []
          exporters: [debug]
