---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: collection
  namespace: '{{ .Release.Namespace }}'
spec:
  mode: deployment
  replicas: {{ .Values.replicas | int }}
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            # Just an example, this is weird to do
            endpoint: ${env:OTELCOL_HTTP_ENDPOINT}
    processors:
      transform:
        trace_statements:
          - context: span
            statements: {{ range .Values.ottlStatements.contextSpan }}
              - '{{ .function }}(attributes[{{ quote .target }}], {{ quote .regex }}, {{ quote .replacement }})'{{end }}
              # Example of how it normally looks:
              # - replace_pattern(attributes["http.url"], "/(pvd|provider-g00dzilla|login|restart)/(.*)\\?.*", "/$1/$2")
    exporters:
      debug:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug]
